print('hello word')
print('hello1', 'hello2', 'hello3')
print(66)
print(66 + 88)
print('包含中文的str')
ord('A')
ord('中')
chr(66)
chr(25991)
'ABC'.encode('ascii')
'中文'.encode('utf-8')
'中文'.encode('ascii')
'中文'.encode('gb2312')
len('ABC')
len('中文')
var = 'Hello, %s' % 'world'
var = 'Hi, %s, you have $%d.' % ('Michael', 1000000)
'Hello, {0}, 成绩提升了 {1:.1f}%'.format('小明', 17.125)
# name = input('请输入你的名字:')
# print(name)
